### ISSUE TITLE
Exception with @MapperScan

### ISSUE THREAD

**Issue by cooper-lyt** [chenggangpro/reactive-mybatis-support#135]
@MapperScan is not work!

```
@SpringBootApplication
@MapperScan({"xx.mapper"})
public class Application {
   ...
}
```

throw exception:

```
Caused by: java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.mybatis.spring.support.SqlSessionDaoSupport.checkDaoConfig(SqlSessionDaoSupport.java:122)
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:73)
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 101 more
```

Change to @Mapper is worked!

**Comment by chenggangpro** [comment]
The original `@MapperScan` was replaced with `@R2dbcMapperScan`.You may try it. For more notes, please check the `Readme.md`'s section [using-in-spring-environment](https://github.com/chenggangpro/reactive-mybatis-support#using-in-spring-environment)

**Comment by cooper-lyt** [comment]
This is my fault. I should have made it clear.
