### ISSUE TITLE
Exception with @R2dbcMapperScan and  @Repository 

### ISSUE THREAD

**Issue by cooperlyt** [chenggangpro/reactive-mybatis-support#139]
@R2dbcMapperScan include a @Repository  throws exception:

`Caused by: java.lang.ClassNotFoundException: net.bytebuddy.renamed.java.lang.Object$ByteBuddy$hogupVqa
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)`

``` java
@R2dbcMapperScan("xxx.r2dbc.mapper")
public class WorkerIdAutoConfigure {
//...
}

@Repository
public interface R2dbcWorkerNodeMapper {
//...
}
```

Just remove @Repository, It's worked!

**Comment by chenggangpro** [comment]
Finished compatible with `r2dbc-spi` both `(0.9.1.RELEASE)` version and `1.0.0.RELEASE` version. See branch: [3.x](https://github.com/chenggangpro/reactive-mybatis-support/blob/3.x)
